name: Container image upstream UI test runner

on:
  push:
    branches:
      - main
    paths:
      - 'testing/package.json'
      - 'testing/package-lock.json'
      - 'testing/UpstreamTestContainerFile'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Log in to Quay.io
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: ./testing
          file: ./testing/UpstreamTestContainerFile
          push: true
          tags: quay.io/kubev2v/forklift-ui-tests:upstream-latest
          build-args: |
            VERSION=${{ github.ref_name }}
            GIT_COMMIT=${{ github.sha }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}

      - name: Logout from Quay.io
        run: docker logout quay.io
